import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { AuthProvider } from '@/contexts/AuthContext';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { UIProvider } from '@/contexts/UIContext';
import { NotificationBar } from '@/components/NotificationBar';
import { GlobalLoading } from '@/components/GlobalLoading';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Yameru',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background`}>
        <AuthProvider>
          <UIProvider>
            <GlobalLoading />
            <NotificationBar />
            <Header />
            <main className="p-4">{children}</main>
            <Footer />
          </UIProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
